---
# tasks file for roles/ssh_key_deploy
- name: Create user {{ new_user }}
  ansible.builtin.user:
    name: "{{ new_user }}"
    state: present
    shell: /bin/bash

- name: Ajouter la clé publique pour l'utilisateur {{ new_user }}
  ansible.builtin.authorized_key:
    user: "{{ new_user }}"
    state: present
    key: "{{ ssh_pub_key }}"
