---
# tasks file for roles/ssh_key_deploy
- name: Create new users
  ansible.builtin.user:
    name: "{{ item.user }}"
    state: present
    shell: /bin/bash
  loop: "{{ new_users }}"

- name: add pub_key
  ansible.builtin.authorized_key:
    user: "{{ item.user }}"
    state: present
    key: "{{ item.ssh_pub_key }}"
  loop: "{{ new_users }}"

- name: add new users to sudoers with full rights and no password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^{{ item.user }} ALL='
    line: "{{ item.user }} {{ item.sudo_line | default('ALL=(ALL:ALL) NOPASSWD:ALL') }}"
    validate: 'visudo -cf %s'
    state: present
  loop: "{{ new_users }}"
  when: item.sudo
